apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node
  labels:
    app: multi-node-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-node
  template:
    metadata:
      labels:
        app: test-node
    spec:
      containers:
      - image: docker.io/rayroestenburg/ssh-server:latest
        imagePullPolicy: Always
        name: multi-node-test
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        - name: ssh
          containerPort: 22
          protocol: TCP
